/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.11 public/rocketLauncher/scene.gltf -t -r public
Author: Ivan008 (https://sketchfab.com/hukan008)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/rocket-launcher-32177fca0bf54bf3a844b3ba61845c28
Title: Rocket Launcher
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    ['4f744618obj_Material_#344_0']: THREE.Mesh
  }
  materials: {
    Material_344: THREE.MeshStandardMaterial
  }
}

export function RocketLauncher(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/rocketLauncher/scene.gltf') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes['4f744618obj_Material_#344_0'].geometry} material={materials.Material_344} />
    </group>
  )
}

useGLTF.preload('/rocketLauncher/scene.gltf')
